project:
  type: book
  output-dir: _book

book:
  output-file: "2025-rtbs-thesis"
  title: |
    Measuring Network Dependencies 
    from Random Walk Activations
  author: "Rachael T.B. Sexton"
  date: "2025"

  abstract: |
      My abstract for this dissertation.
  chapters:
    - index.qmd
    # - 01-intro.qmd
    - 02-structures-spaces.qmd
    - 03-proj-inverse.qmd
    - 04-ordered.qmd
    - references.qmd
  keyword: "demo,test"
  downloads: "pdf"
bibliography: bibliography.bib  
format:
  umd-thesis-pdf:
    keep-tex: true  
    pdf-engine: lualatex
    pdf-engine-opts: 
      - '--no-shell-escape'
      - '--halt-on-error'
  umd-thesis-html: default
  html: default
