project:
  type: book
  output-dir: _book

book:
  title: "Measuring Network Dependencies from Node Activations"
  author: "Rachael T.B. Sexton"
  date: "TBD"

  abstract: |
    This thesis develops a method for inferring dependency networks from binary data by describing and accounting for sources of systematic bias. 
    Node "activation" data is a common source of complex networks, such as   scientific collaboration networks from publications, to keyword and tag co-occurrence graphs from documents, epidemiological networks from infection records, and customer product recommendations from buyer carts, to name only a few.
    However,the way these networks get created often lead to dense edge "hairballs" and heavy post-processing needs. 
    To more accurately reconstruct dependency networks, we propose a flexible technique that generalizes co-occurrence counting, and allows domain-knowledge to inform _why_ nodes activate (and how to use that for inference). 

    Using our technique, we obtain "Desire Path Density" estimates of latent networks: families of possible networks based on probability distributions over individual edge activations, rather than node co-occurrences.
    We show that co-occurrence counting is a special case of this estimatation technique---and that it assumes node activations arise exclusively from cliques.
    This assumption leads to "clique-bias" in the recovered graphs, which results in the unwanted hairball effect. 
    Our method, called _Forest Pursuit_, is a different application of desire path density estimation that attempts to address this bias.
    It assumes node activations are generated by sampling from distributions over dependency trees.
    
    _Forest Pursuit_ outperforms other algorithms at accurate network recovery, is scalable to very large networks sizes, and can be executed in a streaming or parallel manner over observations. 
    It approximates Steiner trees for each set of activated nodes before aggregating them to estimate the latent global network.
    We additionally extend _Forest Pursuit_ to be a probabilistic model whose parameters may be infered through Expectation Maximization.
    This modification shows improved performance over one-shot _Forest Pursuit_, at the cost of computation time. 

    Our introductory chapters provide a unified framework to analyze node activation data and edge (dependency) occurrences in related vector spaces, and provide a taxonomy of network recovery assumption types so that practitioners can find and describe sources of systematic bias from those assumptions.
    Then, along with derivations for Desire Path Density estimation and Forest Pursuit, we verify our method and compare its performance agains others.
    We created a dataset of synthetic experiments (MENDR), made publically available as a reference and test-bench for the community.
    Finally, we use several case studies to demonstrate the impacts of using _Forest Pursuit_ for network analysis in a realistic setting,with insights into the topological differences between networks inferred by other methods and ours.
    By using _Forest Pursuit_, practitioners can correct for clique-bias and better use their latent networks to uncover important behavior of complex systems. 
    
  chapters:
    - index.qmd
    - content/00-intro.qmd
    # - part: 1-00-structures-spaces.qmd
    - part: "A Practitioner's Guide to Network Recovery"
      chapters:
        - content/part1/1-01-matrix-meas.qmd
        - content/part1/1-02-graph-obs.qmd
        - content/part1/1-03-recovery-road.qmd
        # - 1-03-inverse.qmd
    - part: Nonparametric Network Recovery With Random Spanning Forests # 2-00-recovery.qmd # "Recovery from Bipartite Occurence Records"
      chapters:
        - content/part2/2-04-rand-sf.qmd
        - content/part2/2-05-forest-pursuit.qmd
        - content/part2/2-06-latent-forest-alloc.qmd
    - part: Applications & Case Studies # 3-00-application-future.qmd #"Recovery from Sequentially Ordered Jumps"
      chapters: 
        - content/part3/3-07-qualitative.qmd
        - content/part3/3-08-ordered.qmd
        # - content/part3/3-08-conclusion.qmd
    - content/09-conclusion.qmd
    # - part: "conclusion"
      # chapters:
        # - 
    # - appendices:
  keyword: "demo,test"
  downloads: [pdf]
  page-navigation: true
  sidebar:
    collapse-level: 1
bibliography: resource/pubs.bib  
csl: resource/ieee.csl
callout-appearance: minimal
callout-icon: false
filters:
  - pseudocode
#   - diagram
# diagram:
#   engine:
#     tikz:
#       execpath: "~/.TinyTeX/bin/x86_64-linux/pdflatex"
#       header-includes:
#         - '\usepackage{tikz-network}'
#         - '\usetikzlibrary{arrows, shapes}'
format:
  umd-thesis-pdf:
    keep-tex: true  
    indent: true
    pdf-engine: lualatex
    pdf-engine-opts: 
      - '--no-shell-escape'
      - '--halt-on-error'
  html:
    theme: 
      - pandoc
    # css:
      - resource/custom.scss
    sansfont: Cooper Hewitt
    mainfont: Charter
    linkcolor: maroon
    # fontsize: 0.9rem
    linestretch: 1.35
    max-width: 80rem
    page-layout: full
    toc-location: right
    toc-title: "Contents"
    number-sections: false
    reference-location: margin
    # fig-cap-location: margin
    citation-location: margin
    notebook-links: inline
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 400px
      gutter-width: 1.5rem
    include-in-header:
      - resource/flushright.html
