project:
  type: book
  output-dir: _book

book:
  title: "Measuring Network Dependencies from Node Activations"
  author: "Rachael T.B. Sexton"
  date: "2025"

  abstract: |
      My abstract for this dissertation.
  chapters:
    - index.qmd
    - content/0-intro.qmd
    # - part: 1-00-structures-spaces.qmd
    - part: "A Practitioner's Guide to Network Recovery"
      chapters:
        - content/part1/1-01-matrix-meas.qmd
        - content/part1/1-02-graph-obs.qmd
        - content/part1/1-03-recovery-road.qmd
        # - 1-03-inverse.qmd
    - part: Nonparametric Network Recovery With Random Spanning Forests # 2-00-recovery.qmd # "Recovery from Bipartite Occurence Records"
      chapters:
        - content/part2/2-01-rand-sf.qmd
        - content/part2/2-02-forest-pursuit.qmd
        - content/part2/2-03-latent-forest-alloc.qmd
    - part: Applications & Extentions # 3-00-application-future.qmd #"Recovery from Sequentially Ordered Jumps"
      chapters: 
        - content/part3/3-06-qualitative.qmd
        - content/part3/3-07-ordered.qmd
        - content/part3/3-08-conclusion.qmd
    # - part: "conclusion"
      # chapters:
        # - 
    # - appendices:
  keyword: "demo,test"
  downloads: [pdf]
  page-navigation: true
  sidebar:
    collapse-level: 1
bibliography: resource/pubs.bib  
csl: resource/ieee.csl
callout-appearance: simple
callout-icon: false
filters:
  - pseudocode
#   - diagram
# diagram:
#   engine:
#     tikz:
#       execpath: "~/.TinyTeX/bin/x86_64-linux/pdflatex"
#       header-includes:
#         - '\usepackage{tikz-network}'
#         - '\usetikzlibrary{arrows, shapes}'
format:
  umd-thesis-pdf:
    keep-tex: true  
    indent: true
    pdf-engine: lualatex
    pdf-engine-opts: 
      - '--no-shell-escape'
      - '--halt-on-error'
  html:
    theme: 
      - pandoc
    # css:
      - resource/custom.scss
    sansfont: Cooper Hewitt
    mainfont: Charter
    linkcolor: maroon
    # fontsize: 0.9rem
    linestretch: 1.35
    max-width: 80rem
    page-layout: full
    toc-location: right
    toc-title: "Contents"
    number-sections: false
    reference-location: margin
    # fig-cap-location: margin
    citation-location: margin
    notebook-links: inline
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 400px
      gutter-width: 1.5rem
