project:
  type: book
  output-dir: _book

book:
  title: "Measuring Network Dependencies from Node Activations"
  author: "Rachael T.B. Sexton"
  date: "2025"

  abstract: |
      My abstract for this dissertation.
  chapters:
    - index.qmd
    # - 01-intro.qmd
    - 02-structures-spaces.qmd
    - 03-proj-inverse.qmd
    - 04-forest-pursuit.qmd
    - 05-ordered.qmd
    - references.qmd
  keyword: "demo,test"
  downloads: "pdf"
bibliography: pubs.bib  
csl: ieee.csl
format:
  umd-thesis-pdf:
    keep-tex: true  
    indent: true
    pdf-engine: lualatex
    pdf-engine-opts: 
      - '--no-shell-escape'
      - '--halt-on-error'
  html: default
