project:
  type: book
  output-dir: _book

book:
  title: "Measuring Network Dependencies from Node Activations"
  author: "Rachael T.B. Sexton"
  date: "2025"

  abstract: |
      My abstract for this dissertation.
  chapters:
    - index.qmd
    - 0-intro.qmd
    # - part: 1-00-structures-spaces.qmd
    - part: "A Practitioner's Guide to Network Recovery"
      chapters:
        - 1-01-matrix-meas.qmd
        - 1-02-graph-obs.qmd
        - 1-03-recovery-road.qmd
        # - 1-03-inverse.qmd
    - part: 2-00-recovery.qmd # "Recovery from Bipartite Occurence Records"
      chapters:
        - 2-01-rand-sf.qmd
        - 2-02-forest-pursuit.qmd
        - 2-03-latent-forest-alloc.qmd
    - part: 3-00-application-future.qmd #"Recovery from Sequentially Ordered Jumps"
      chapters: 
        - 3-06-qualitative.qmd
        - 3-07-ordered.qmd
        - 3-08-conclusion.qmd
    # - part: "conclusion"
      # chapters:
        # - 
    # - appendices:
  keyword: "demo,test"
  downloads: "pdf"
  page-navigation: true
  sidebar:
    collapse-level: 1
bibliography: pubs.bib  
csl: ieee.csl
# filters:
#   - diagram
# diagram:
#   engine:
#     tikz:
#       execpath: "~/.TinyTeX/bin/x86_64-linux/pdflatex"
#       header-includes:
#         - '\usepackage{tikz-network}'
#         - '\usetikzlibrary{arrows, shapes}'
format:
  umd-thesis-pdf:
    keep-tex: true  
    indent: true
    pdf-engine: lualatex
    pdf-engine-opts: 
      - '--no-shell-escape'
      - '--halt-on-error'
  html:
    theme: 
      - pandoc
    # css:
      - custom.scss
    sansfont: Cooper Hewitt
    mainfont: Charter
    linkcolor: maroon
    # fontsize: 0.9rem
    linestretch: 1.35
    max-width: 750px
    page-layout: full
    toc-location: right
    toc-title: "Contents"
    number-sections: false
    reference-location: margin
    fig-cap-location: margin
    citation-location: margin
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 300px
      gutter-width: 1.5rem
