project:
  type: book
  output-dir: _book

book:
  title: "Measuring Network Dependencies from Node Activations"
  author: "Rachael T.B. Sexton"
  date: "2025"

  abstract: |
      My abstract for this dissertation.
  chapters:
    - index.qmd
    - 0-intro.qmd
    - part: 1-00-structures-spaces.qmd
      chapters:
        - 1-01-graph-obs.qmd
        - 1-02-projection.qmd
        - 1-03-inverse.qmd
    - part: 2-00-recovery.qmd # "Recovery from Bipartite Occurence Records"
      chapters:
        - 2-04-forest-pursuit.qmd
        - 2-05-latent-forest-alloc.qmd
    - part: 3-00-application-future.qmd #"Recovery from Sequentially Ordered Jumps"
      chapters: 
        - 3-06-qualitative.qmd
        - 3-07-ordered.qmd
        - 3-08-conclusion.qmd
    # - part: "conclusion"
      # chapters:
        # - 
    # - appendices:
  keyword: "demo,test"
  downloads: "pdf"
bibliography: pubs.bib  
csl: ieee.csl
format:
  umd-thesis-pdf:
    keep-tex: true  
    indent: true
    pdf-engine: lualatex
    pdf-engine-opts: 
      - '--no-shell-escape'
      - '--halt-on-error'
  html: default
